# Generated by Django 3.2.4 on 2021-08-07 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.SlugField(max_length=30)),
                ('msg_chat', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nick_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nick_name_chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
