# Generated by Django 3.2.4 on 2021-08-19 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
