# Generated by Django 3.2.4 on 2021-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_status_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
